apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 5m
  chart:
    spec:
      chart: longhorn
      version: "1.10.1"
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  install:
    createNamespace: true
  values:
    longhorn:
      replicas: 1
    csi:
      attacher:
        replicas: 1
      provisioner:
        replicas: 1
      resizer:
        replicas: 1
      snapshotter:
        replicas: 1
    defaultSettings:
      defaultDataPath: "/var/lib/longhorn"
      defaultDataLocality: "best-effort"
      defaultClassReplicaCount: 1
      mkfsExt4Parameters: "-F"
      guaranteedInstanceManagerCPU: "0.5"
      taintTolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
    preUpgradeChecker:
      jobEnabled: false
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 1
      defaultFsType: ext4
      reclaimPolicy: Delete
      defaultMkfsParams: "-F"
    longhornManager:
      resources:
        limits:
          cpu: 200m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 128Mi
    longhornDriver:
      resources:
        limits:
          cpu: 200m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 128Mi
    ingress:
      enabled: false
