apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: it-tools
  namespace: flux-system
spec:
  path: ./apps/it-tools
  interval: 10m
  prune: true
  wait: true
  dependsOn:
    - name: infrastructure
