apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system   # Flux watches the HelmRelease here
spec:
  interval: 10m
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      version: 1.19.1
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  targetNamespace: cert-manager
  install:
    createNamespace: true
