apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-issuer
  namespace: flux-system
spec:
  interval: 5m
  path: ./infrastructure/cert-manager/config/cluster-issuer
  prune: true
  wait: true
  dependsOn:
    - name: infrastructure   
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system